version: "3.0"
services:
  container_mysql:
    image: mysql:5.7.13
    environment:
      MYSQL_DATABASE: "golang_posts"
      MYSQL_ROOT_PASSWORD: "root"

  container_posts:
    image: posts-api-mysql:latest
    ports:
      - 3000:3000
    depends_on:
      - container_mysql